import numpy as np
import matplotlib.pyplot as plt

def read_simulation_output(file_path):
    """
    Reads the output from the simulation generated by the C++ code.
    Assumes the format is tab-separated values with each time step on a new line.
    """
    data = []
    with open(file_path, 'r') as f:
        for line in f:
            values = line.strip().split('\t')
            # Check if the line contains the expected number of elements
            num_particles = int(values[0])
            if len(values) == (num_particles * 11) + 1:  # 1 for the number of particles
                particle_data = np.array(values[1:], dtype=float).reshape(num_particles, 11)
                data.append(particle_data)
            else:
                print(f"[Warning] Skipping line with unexpected length: {len(values)} vs expected {num_particles * 11 + 1}")
    
    return np.array(data)

def plot_positions(data, num_steps, num_particles, output_filename="simulation.png"):
    """
    Plots the positions of the particles over the time steps.
    """
    fig, ax = plt.subplots()

    for step in range(0, num_steps, 10):  # Change the step interval for plotting frequency
        positions = data[step, :, 1:4]  # Extract positions (x, y, z) for all particles
        ax.scatter(positions[:, 0], positions[:, 1], label=f"Step {step}")

    ax.set_xlabel('X Position')
    ax.set_ylabel('Y Position')
    ax.set_title('Particle Positions Over Time')
    ax.legend()
    plt.savefig(output_filename)
    plt.show()

def main():
    # File containing the output from your C++ simulation (e.g., "simulation_output.txt")
    file_path = 'simulation_output.txt'
    num_steps = 100  # Total number of steps to process
    num_particles = 10  # Number of particles in the simulation
    
    # Read the simulation output
    data = read_simulation_output(file_path)
    
    # Verify the shape of the data
    print(f"[DEBUG] Data shape: {data.shape}")

    # Reshape the data to have a time axis
    # Note: You might need to adjust num_steps if the data is not exactly as expected
    data = data.reshape(num_steps, num_particles, -1)  # Reshape to (steps, particles, values)
    
    # Plot the positions of the particles
    plot_positions(data, num_steps, num_particles)

if __name__ == "__main__":
    main()

